import Project, { Download, Platform } from "./projects/lib/project";

export const IP = "194.163.45.40"

export const PROJECTS:{[index:string]:Project} = {
	"Neat Object Notation":new Project("favicon.ico", "Neat Object Notation", [0,6,16], "A smart and modular object notation.", ["neat", "package", "compiler", "serialize", "serializer", "rust", "python", "notation", "object", "config", "interpreter", "serialization", "dict", "cargo", "pyo3", "pip", "module", "pypi", "list", "dictionary", "datastructure", "datastructures"], [new Download("Neat.zip", "Neat Object Notation", "zip", [0,6,16], Platform.Win)])
	.set_body("Neat is scaleable and versatile.  Neat is designed to be used as a python module."),
	"Earwig Web Framework":new Project("favicon.ico", "Earwig Web Framework", [0,11,2], "A web framework that simplifies python web development.", ["web", "framework", "python", "website", "site", "werkzeug", "api"], [new Download("Earwig.zip", "Earwig Web Framework", ".zip", [0,11,2], Platform.All)])
	.set_body("The Earwig Web Framework is designed to be used not as a module, but as a project directory.  To get started, download the Earwig Web Framework development kit."),
	"Twig Web Framework":new Project("favicon.ico", "Twig Web Framework", [0,5,0], "A web web framework built with the python socket module that functions similarly to flask.", ["website", "site", "python", "paste", "bin", "api", "rest", "twig", "sockets", "js", "javascript", "java", "script", "flask"]),
	"Python Image Processor":new Project("favicon.ico", "Python Image Processor", [0,2,1], "A python image matrix processor made using numpy and pillow. This module features a saturate, desaturate, contrast, decontrast, mosaic, mosaic blur, black and white, and a cell shading filter that works by altering the image matrix in python directly.", ["image", "module", "processing", "python", "pil", "pillow", "numpy", "matrix", "blur", "cell", "shade"]),
	"Portfolio Site":new Project("favicon.ico", "Portfolio Site", [0,1,0], "William A. Lim's portfolio site powered by Next.js, scss and typescript", ["next", "next.js", "react.js", "react", "website", "site", "react", "typescript", "ts", "js", "javascript", "java", "script", "css", "scss"]),
	"Fulcrum":new Project("favicon.ico", "Fulcrum", [0,8,9], "A scripting language written in rust.", ["fulcrum", "scripting", "language", "ful", "functional", "programming", "minimal", "input", "output"], [new Download("Fulcrum_Windows.zip", "Fulcrum", "zip", [0,8,9], Platform.Win), new Download("Fulcrum_Mac.zip", "Fulcrum", "zip", [0,8,9], Platform.Mac), new Download("Fulcrum_Linux.tar.gz", "Fulcrum", "tar.gz", [0,8,9], Platform.Lin)])
  };